# Generated by Django 4.0.3 on 2022-04-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=24)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
